apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
    - host: wil-app
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: wil-service
              port:
                number: 80
